# this is so ruby and other unnecessary stuff wont be installed
language: generic

# download and unpack the stack executable
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

cache:
  directories:
    - $HOME/.stack

# run the tests through stack
script: stack --no-terminal --skip-ghc-check test
